language: go

go:
- 1.14

before_install:
- go mod tidy

script:
- go test ./... -race -coverprofile=coverage.txt -covermode=atomic
- go build -tags netgo -a -v ./cmd/s3analyser/
- GOOS=windows GOARCH=amd64 go build -tags netgo -a -v ./cmd/s3analyser/

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: qfiWYFOb9PqiTE3imOXTHfkBu7k0dX9BxHi8yFUbH2eczSV5W8nbS7DfPlTsyv9EpmvGvcRiuZ0Jat6YeD2EDkjGsJWHZlWh1xPhCaR2I1viqmTJsw/YSW+B4xEr6MrSkkLWuIPXsKu5+J+yrhdEqJOv9Pjm0x0ursUvPDtJt1YftBNWqHqTCA3VU5UIIs5fhqlX9G7tTsmk0BAfbA7cu1grFsXi5iZrYsMxHw/9TVFoj7S8b3CQUCzg3imHc/FMay2dZcABKiOyXQ773GJXNdC+56agQwZl6pjh7gqEMAlb9Txkf+CVEPS/Jn2uRk4MCVzTTYa5dMz9ujLifzlVln+n2ZfRKgM2LtliE+CXVBa6y1jKpydo7B2K8oQZ7cN1Y2d6+RcjHz8WowCjNs1VXk/fx7CKYFZ4IzJMcxAx+IHRgWbpQB5Dx+9xcImRBPYscu8MVzeJe7wlrrSchjsqwHgnLP11Ws9BMsyT5B5+7RAAs+sROOqYl9K6FwrAXrCM/gKu95OVaaaB2xU6iA3azNvTy+4KFCwYKGlEQQ2l1tGXJqJJZoQc+1WygKmLPGhE/D85qfRgl8k2qBB8RE3WOS1CypgTgopGTZe1pa9sCpLpqrC/g0fZiKpyfU94IOqF2ig6KHx6eL6wpVyOGo0XfD+SnMsRLuvQXGcYFCsTsHU=
  file:
    - s3analyser
    - s3analyser.exe
  skip_cleanup: true
  on:
    repo: SimpleApplicationsOrg/s3analyser
    tags: true
