language: go
sudo: required
dist: precise

go:
  - 1.9

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y

install:
  - glide install

script:
  - ./go.test.sh
  - go build -tags netgo -a -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ ! -z "$TRAVIS_TAG"]; then ./docker.push.sh   fi