language: go
sudo: required
dist: precise
go:
- 1.9

before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y

install:
- glide install

script:
- "./go.test.sh"
- go build -tags netgo -a -v
- GOOS=windows GOARCH=amd64 go build -tags netgo -a -v

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: QDNehB/SgG8BSRKUd2VqGhIHiQSDKjw/oMXMuTE0vHUjT2EfE1+YwqPutYXBoYK2SLj+fegfdGg2n0N3DWz/hwYKYqsKSamNmvcqcCacWTCXiUPnkf0bfOYBa8uXeP6qPx+9vtlHvFeDspq02a73E6orbFgjJbP3scDXU40V9GLk32I1kwpUVVnEHYL3FO/BeIiWFaDQomPO+aAI7IQI8jtGaONxIwHFIU2gmt4/TdagffaZyXc8Cwxy9TN64aoV3uBNLmOW0PYaeC49AeykhIvExP8vJjlYK9LWQp9+5+F88SSxVJze6+Tkwtj3Q+JrIt8/+bNu0KCITG5NZLXLm13rSVVYqSiY8fvI4MS4b5YYF8aWMheHehQAaMZ0pp2WqNKBKlmThh1LOLPk2ARNhWBuElQw0zLExC6a+lpXg4fVkGxTl6cnatccdEikjKk1bARFdNsevQfSE1BKnmv3FkeVenopvUQO+4KKoS9mDWv4jvBUON/Lo7Tx/oYgP6NLMqwaNySQfv8FthpeSeBAX3Wg7LEbQmJD2+eERpubiaozycxco5OeRHpJYgjmZsckbTcn8AZLxoPhyrmRJ40s+X8EmO+Gk6fC8qHuiGYWEFoy3D7+iWxJhLdxiSIEL1qZxPQeBGVsLhVxo1al/dXyPDOi3FTZX4Lo6tNE00oWx7Q=
  file:
    - s3analyser
    - s3analyser.exe
  skip_cleanup: true
  on:
    repo: SimpleApplicationsOrg/s3analyser
    tags: true
