version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/SimpleApplicationsOrg/s3analyser
    steps:
      - checkout

      - run: ./go.test.sh
      - run: go build -tags netgo -a -v

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.11.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          if [[ ! -z "$CIRCLE_TAG" ]]; then
            docker build . -t s3analyser/s3analyser:$CIRCLE_TAG;      # (4)
            docker login -u $DOCKER_SAT_USER -p $DOCKER_SAT_PASSWORD; # (5)
            docker push s3analyser/s3analyser:$CIRCLE_TAG;
          fi